### ISSUE TITLE
Troca de Dominio da API da Asaas

### ISSUE THREAD

**Issue by leandrompaiva** [boskyn9/JAsaas#12]
Prezados, uso essa implementação em um sistema pessoal, e ela é simplesmente SENSACIONAL. Recebi um e-mail da Asaas, informando uma alteração no ENDPOINT principal das chamadas. O que eu estou buscando aqui é confirmar que o único lugar que devo alterar na implantação dela aqui, está nessa classe abaixo, correto?

CLASSE: AbstractConnection

PACOTE: .asaas.api

private static final String ENDPOINT_PRODUCAO = "https://www.asaas.com/api/v3";
private static final String ENDPOINT_HOMOLOGACAO = "https://sandbox.asaas.com/api/v3";

Saberia informar se preciso trocar o endpoint, em qualquer outro local? Pessoalmente não localizei)

**Comment by boskyn9** [comment]
Só ai mesmo.

**Comment by boskyn9** [comment]
a versão 3.8.4 está com o novo endereço
