### ISSUE TITLE
Duvida: essa versão é mantida?

### ISSUE THREAD

**Issue by valeriolopes** [boskyn9/JAsaas#4]
Pessoal, esse SDK é estavel? Voces usam em produção? Ou o projeto foi abandonado?

**Comment by laercioskt** [comment]
Olá, 

Também considerando usar esse repo, mas realizando alguns testes percebi que uma estrutura estava desatualizada, então, acredito que o pessoal tenha abandonado.

Não sei se vou usar o Asaas ainda, mas devo comitar no meu fork eventuais ajustes e melhorias.

**Comment by boskyn9** [comment]
Usamos sim. Atualmente está em dois projetos internos usando a V3. Infelizmente não colocamos todas a funcionalidades em uso. Nos sistemas usamos um controle de mensalidade interno, então o uso da API está em grande parte na criação de cliente, boletos, baixas de boletos e edições dessas mesmas entidades. O controle interno de mensalidade seria a geração de boletos via jobs(como na imagem abaixo), baseado em configurações no próprio sistema do cliente. Então, não usamos a ferramenta de mensalidade existente no Asaas. Não sei se ficou claro... :/  

![image](https://user-images.githubusercontent.com/11460262/129814860-5c3e90d4-0a45-4eef-ae7e-4d611412d68c.png)

**Comment by laercioskt** [comment]
Acredito que ficou claro, vocês usam apenas a emissão de boletos e não a recorrência da plataforma asaas.

Obrigado por compartilhar a API por aqui!

**Comment by boskyn9** [comment]
Respondido.
