### ISSUE TITLE
SDK está em produção?

### ISSUE THREAD

**Issue by rafaeldalbosco** [boskyn9/JAsaas#7]
Olá @boskyn9 gostaria de informações como anda o desenvolvimento dessa SDK, ela já está em produção?
Quais os recursos suportados?

**Comment by boskyn9** [comment]
Boa tarde @rafaeldalbosco , está em produção sim. Infelizmente não finalizamos o README e nem fizemos os testes devidos para o mecanismo de assinatura. Aqui na empresa utilizamos o controle no sistema para geração das faturas. Então, o mecanismo de assinatura do asaas não foi utilizado. Caso queira contribuir... :)

**Comment by rafaeldalbosco** [comment]
Perfeito @boskyn9 estou avaliando a viabilidade dessa integração, mas com certeza se evoluir irei contribuir.
